spring.application.name=Group-Service
spring.config.import=optional:file:.env[.properties]

server.port=${APPLICATION_PORT:3001}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/scrumdapp}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DATABASE_USER:myuser}
spring.datasource.password=${DATABASE_PASSWORD:secret}

spring.jpa.properties.hibernate.jdbc.batch_size=20