CREATE TABLE groups
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(255)                             NOT NULL,
    group_owner           INTEGER                                  NOT NULL,
    background_preference INTEGER,
    is_active             BOOLEAN                                  NOT NULL,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);
CREATE TABLE group_features
(
    key         INTEGER      NOT NULL,
    description VARCHAR(255) NOT NULL,
    CONSTRAINT pk_group_features PRIMARY KEY (key)
);

ALTER TABLE group_features
    ADD CONSTRAINT FK_GROUP_FEATURES_ON_KEY FOREIGN KEY (key) REFERENCES groups (id);
CREATE TABLE group_users
(
    user_id  INTEGER NOT NULL,
    group_id INTEGER NOT NULL,
    CONSTRAINT pk_groupusers PRIMARY KEY (user_id, group_id)
);

ALTER TABLE group_users
    ADD CONSTRAINT FK_GROUPUSERS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);
CREATE TABLE groups
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(255)                             NOT NULL,
    group_owner           INTEGER                                  NOT NULL,
    background_preference INTEGER,
    is_active             BOOLEAN                                  NOT NULL,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);