CREATE SEQUENCE IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE group_features
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id    INTEGER,
    description VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_group_features PRIMARY KEY (id)
);

CREATE TABLE group_users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  INTEGER                                  NOT NULL,
    group_id INTEGER                                  NOT NULL,
    CONSTRAINT pk_group_users PRIMARY KEY (id)
);

CREATE TABLE groups
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(255)                             NOT NULL,
    group_owner           INTEGER                                  NOT NULL,
    background_preference INTEGER,
    is_active             BOOLEAN                                  NOT NULL,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         INTEGER NOT NULL,
    discord_id BIGINT,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    avatar_url VARCHAR(255),
    role       VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE group_features
    ADD CONSTRAINT FK_GROUP_FEATURES_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE group_users
    ADD CONSTRAINT FK_GROUP_USERS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE group_users
    ADD CONSTRAINT FK_GROUP_USERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);